In [1]:
import pandas as pd
import numpy as np
ser = pd.Series([0,1, np.nan, "hello", complex(3,2)])
ser

0         0
1         1
2       NaN
3     hello
4    (3+2j)
dtype: object

In [2]:
import pandas as pd
ser = pd.DataFrame([1, 2 , "Apple", 0.4, "01-04-2025"], columns = ["Values"], index = ["A", "B", "C", "D", "E"])
ser

       Values
A           1
B           2
C       Apple
D         0.4
E  01-04-2025

In [ ]:
import pandas as pd
data = {"name": ["Alice", "Roger", "Dean", "Garret", "Hannah"], "age": [26, 43, 28, 28, 19], "profession": ["Engineer", "CEO", "Hockey Player", "Hockey Player", "Singer"]}
df = pd.DataFrame(data)
df

     name  age     profession
0   Alice   26       Engineer
1   Roger   43            CEO
2    Dean   28  Hockey Player
3  Garret   28  Hockey Player
4  Hannah   19         Singer

In [3]:
import pandas as pd
data = {"name": ["Alice", "Roger", "Dean", "Garret", "Hannah"], "age": [26, 43, 28, 28, 19], "profession": ["Engineer", "CEO", "Hockey Player", "Hockey Player", "Singer"]}
df = pd.DataFrame(data)

for index , rows in df.iterrows():
    print(index, ":", rows)

0 : name             Alice
age                 26
profession    Engineer
Name: 0, dtype: object
1 : name          Roger
age              43
profession      CEO
Name: 1, dtype: object
2 : name                   Dean
age                      28
profession    Hockey Player
Name: 2, dtype: object
3 : name                 Garret
age                      28
profession    Hockey Player
Name: 3, dtype: object
4 : name          Hannah
age               19
profession    Singer
Name: 4, dtype: object

In [7]:
import pandas as pd
data = {"name": ["Alice", "Roger", "Dean", "Garret", "Hannah"], "age": [26, 43, 28, 28, 19], "profession": ["Engineer", "CEO", "Hockey Player", "Hockey Player", "Singer"]}
df = pd.DataFrame(data)

for rows in df.itertuples():
    print(rows)

Pandas(Index=0, name='Alice', age=26, profession='Engineer')
Pandas(Index=1, name='Roger', age=43, profession='CEO')
Pandas(Index=2, name='Dean', age=28, profession='Hockey Player')
Pandas(Index=3, name='Garret', age=28, profession='Hockey Player')
Pandas(Index=4, name='Hannah', age=19, profession='Singer')

In [9]:
import pandas as pd
import numpy as np
data = {"name": ["Alice", "Roger", "Dean", "Garret", "Hannah"], "age": [26, 43, 28, 28, 19], "profession": ["Engineer", "CEO", "Hockey Player", "Hockey Player", "Singer"]}
df = pd.DataFrame(data)

df.age.apply(np.sqrt)

0    5.099020
1    6.557439
2    5.291503
3    5.291503
4    4.358899
Name: age, dtype: float64

In [10]:
df

     name  age     profession
0   Alice   26       Engineer
1   Roger   43            CEO
2    Dean   28  Hockey Player
3  Garret   28  Hockey Player
4  Hannah   19         Singer

In [19]:
list = pd.MultiIndex.from_frame(df)
list  

#stores in a list format and helps to access the data in a more efficient way using the index values. It is used to create a multi-level index for a DataFrame, 
#allowing for more complex data structures and easier data manipulation.

list[1][2]
list[0][1]

np.int64(26)

In [ ]:
df.reindex([3,4,1,0,2]) #rearrange the order of the rows based on the specified index values. It allows you to change the order of the rows in a DataFrame according to a new index.

     name  age     profession
3  Garret   28  Hockey Player
4  Hannah   19         Singer
1   Roger   43            CEO
0   Alice   26       Engineer
2    Dean   28  Hockey Player

In [9]:
D1 = {"ID": [1, 2, 3, 4, 5], "Emp Name": ["Silvie", "Drake", "Lucas", "Mia", "Ethan"], "Department": ["HR", "Finance", "IT", "Marketing", "Sales"], "Post": ["Manager", "Analyst", "Developer", "Executive", "Associate"]}
D2 = {"ID": [6,7,8,9,10,11], "Emp Name": ["Olivia", "Liam", "Emma", "Noah", "Nathan", "Brooke"], "Department": ["HR", "IT", "IT", "Finance","Sales", "HR"]}

pd.merge(pd.DataFrame(D1), pd.DataFrame(D2), on = "ID", how = "outer") 
#merge the two DataFrames based on the common column "ID". The "outer" parameter specifies that all rows from both DataFrames should be included in the result, even if there are no matching values in the "ID" column.

    ID Emp Name_x Department_x       Post Emp Name_y Department_y
0    1     Silvie           HR    Manager        NaN          NaN
1    2      Drake      Finance    Analyst        NaN          NaN
2    3      Lucas           IT  Developer        NaN          NaN
3    4        Mia    Marketing  Executive        NaN          NaN
4    5      Ethan        Sales  Associate        NaN          NaN
5    6        NaN          NaN        NaN     Olivia           HR
6    7        NaN          NaN        NaN       Liam           IT
7    8        NaN          NaN        NaN       Emma           IT
8    9        NaN          NaN        NaN       Noah      Finance
9   10        NaN          NaN        NaN     Nathan        Sales
10  11        NaN          NaN        NaN     Brooke           HR

In [ ]:
D1 = {"ID": [1, 2, 3, 4, 5], "Emp Name": ["Silvie", "Drake", "Lucas", "Mia", "Ethan"], "Department": ["HR", "Finance", "IT", "Marketing", "Sales"], "Post": ["Manager", "Analyst", "Developer", "Executive", "Associate"]}
D2 = {"ID": [6,7,8,9,10,11], "Emp Name": ["Olivia", "Liam", "Emma", "Noah", "Nathan", "Brooke"], "Department": ["HR", "IT", "IT", "Finance","Sales", "HR"]}
pd.concat([pd.DataFrame(D1), pd.DataFrame(D2)], axis = 0, ignore_index = True)
#concatenate the two DataFrames vertically (stacking them on top of each other) and reset the index of the resulting DataFrame. The "ignore_index=True" parameter ensures that the index
#axis=0 means we are concatenating along the rows (vertically). This will combine the two DataFrames into a single DataFrame with all the rows from both D1 and D2, and the index will be reset to a default integer index.
#The resulting DataFrame will contain all the rows from both D1 and D2, with the index starting from 0 and incrementing by 1 for each row.

    ID Emp Name Department       Post
0    1   Silvie         HR    Manager
1    2    Drake    Finance    Analyst
2    3    Lucas         IT  Developer
3    4      Mia  Marketing  Executive
4    5    Ethan      Sales  Associate
5    6   Olivia         HR        NaN
6    7     Liam         IT        NaN
7    8     Emma         IT        NaN
8    9     Noah    Finance        NaN
9   10   Nathan      Sales        NaN
10  11   Brooke         HR        NaN

In [31]:
import pandas as pd
data = {"name": ["Alice", "Roger", "Dean", "Garret", "Hannah"], "age": [26, 43, 28, 28, 19], "profession": ["Engineer", "CEO", "Hockey Player", "Hockey Player", "Singer"]}

df = pd.DataFrame(data)
df[["name", "profession"]].applymap(lambda x: len(x)) 
#applymap() is a method in pandas that allows you to apply a function to each element of a DataFrame. In this case, the lambda function is used to calculate the length of each string in the "name" and "profession" columns. The result will be a new DataFrame where each value represents the length of the corresponding string from the original DataFrame.


df[["name", "profession"]].apply(lambda x: len(x), axis = 0) 
df[["name", "profession"]].apply(lambda x: len(x), axis = 1)

/var/folders/pw/jbfphk8d6zbb1rrwjlmnv94w0000gn/T/ipykernel_68386/1482449425.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[["name", "profession"]].applymap(lambda x: len(x))

0    2
1    2
2    2
3    2
4    2
dtype: int64

In [43]:
data = {"name": ["Alice", "Roger", "Dean", "Garret", "Hannah"], "age": [26, 43, 28, 28, 19], "profession": ["Engineer", "CEO", "Hockey Player", "Hockey Player", "Singer"]}
df = pd.DataFrame(data)

# df["profession"] = df.Category(df["profession"]).codes
df["profession"] = df["profession"].astype("category").cat.codes
df

     name  age  profession
0   Alice   26           1
1   Roger   43           0
2    Dean   28           2
3  Garret   28           2
4  Hannah   19           3

In [4]:
import pandas as pd
data = {"name": ["Alice", "Roger", "Dean", "Garret", "Hannah"], "age": [26, 43, 28, 28, 19], "profession": ["Engineer", "CEO", "Hockey Player", "Hockey Player", "Singer"]}
df = pd.DataFrame(data)

dummy = pd.get_dummies(df, columns = ["profession"], dtype = int)
dummy

,name,age,profession_CEO,profession_Engineer,profession_Hockey Player,profession_Singer
0,Alice,26,0,1,0,0
1,Roger,43,1,0,0,0
2,Dean,28,0,0,1,0
3,Garret,28,0,0,1,0
4,Hannah,19,0,0,0,1

In [17]:
import pandas as pd
data = {"name": ["Alice", "Roger", "Dean", "Garret", "Hannah"], "age": [26, 43, 28, 28, 19], "profession": ["Engineer", "CEO", "Hockey Player", "Hockey Player", "Singer"]}
df = pd.DataFrame(data)

x = df.age.mean()
y = df.age.median()
z = df.age.mode()
a = df.age.std()
b = df.age.var()

print(x)
print(y)
print(z)
print(a)
print(b)

28.8
28.0
0    28
Name: age, dtype: int64
8.757853618324527
76.70000000000002

In [18]:
mask = df["profession"] == "Hockey Player"
mask

0    False
1    False
2     True
3     True
4    False
Name: profession, dtype: bool

In [25]:
data = {"name": ["Alice", "Roger", "Dean", "Garret", "Hannah"], "age": [26, 43, 28, 28, 19], "profession": ["Engineer", "CEO", "Hockey Player", "Hockey Player", "Singer"]}
df = pd.DataFrame(data)

sort = df.sort_values(by = 'name', ascending = False, inplace = False)
sort

     name  age     profession
1   Roger   43            CEO
4  Hannah   19         Singer
3  Garret   28  Hockey Player
2    Dean   28  Hockey Player
0   Alice   26       Engineer